[package]
name = "rqldb-shell"
version = "0.1.0"
edition = "2021"

[dependencies]
rqldb = { path = "../db" }
rqldb-persist = { path = "../persist" }
rustyline = "9.1.2"
clap = { version = "3.2.25", features = ["derive"] }
