[package]
name = "rqldb"
authors.workspace = true
description.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[dev-dependencies]
criterion = "0.3.6"
lazy_static = "1.4.0"

[[bench]]
name = "bench"
harness = false
