[package]
name = "rqldb-persist"
version = "0.1.0"
edition = "2021"

[dependencies]
rqldb = { path = "../db" }
bson = "2.9.0"

[dev-dependencies]
criterion = "0.3.6"

[[bench]]
name = "bench"
harness = false
